### findAll
GET http://localhost:3000/api/channel/
Content-type : application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTYyOTU0NjA4NiwiZXhwIjoxNjI5NTQ2MDg3fQ.lDHHJMFYAUq-OFazBhUmoZAGjHcxafjRE3M0GIjDXhM



### findOne
GET http://localhost:3000/channel/3


### create
POST http://localhost:3000/channel/
Content-type : application/json

{   
    "channel" : {
        "name"   : "nom de mon group channelB",
        "description" : null,
        "channel_group_id" : 3
    }

}

### modify
PUT http://localhost:3000/channel/3
Content-type : application/json

{
    "channel" : {
        "name"     : "Prout channel",
        "description" : null,
        "channel_group_id" : 3     
    }

}

### remove
DELETE http://localhost:3000/channel/3
